GET http://localhost:5007/comments/9021793848917992

####
GET http://localhost:5007/posts/

####
GET http://localhost:5007/posts

####

POST http://localhost:5007/comments
content-type: application/json

{   
  "authorEmail": "james@bond.com",
  "text": "this is a test comment",
  "postId": "3083126839342818"
}

####

POST http://localhost:5007/posts
content-type: application/json

{
  
  "body": "This is a test post.",
  "author": "",
  "tags": ["test", "example"],
  "date": "2022-04-03T12:00:00Z"
}

###
POST http://localhost:5007/posts
content-type: application/json

{
  "title": "Test Post",
  "body": "This is a test post.",
  "author": "John Doe",
  "tags": ["test", "example"],
  "date": "2022-04-03"
}